name: Docker Image CI

on:
  push:
    branches:
      - main
      
env:
  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_NAME: ${{ secrets.DB_NAME }}

jobs:
  build-image:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      env:
        IMAGE_VERSION: ${{ github.run_number }}
      run: make docker-build

  rm-previous-docker-resources:
    runs-on: self-hosted
    needs: build-image
    steps:
    - name: Remove existing container
      run: make docker-clean
    - name: Remove previous images
      run: |
          IMAGE_NAME=inanny-bot
          IMAGE_VERSION=${{ github.run_number }}
          IMAGES=$(docker images --format "{{.Repository}}:{{.Tag}}" | grep "$IMAGE_NAME")
          echo $IMAGES
          for IMAGE in $IMAGES; do
            if [[ $IMAGE != *"$IMAGE_VERSION" ]]; then
              docker rmi $IMAGE || true
            fi
          done
  
  db-migrate:
    runs-on: self-hosted
    steps:
      - name: Migrate database
        run: make db-migrate
  
  run-container:
    runs-on: self-hosted
    needs: [rm-previous-docker-resources, db-migrate]
    steps:
    - name: Run the Docker container
      env:
        IMAGE_VERSION: ${{ github.run_number }}
      run: make docker-run
